// Generated by https://quicktype.io

export interface LoginResponse {
    isSuccess: boolean;
    message:   string;
    data:      Data;
}

export interface Data {
    id:       string;
    fullName: string;
    email:    string;
    image:    string;
    userType: number;
    token:    string;
    isValid:  boolean;
    isEmailConfirm:boolean
}
