// Generated by https://quicktype.io

export interface Posts {
    isSuccess: boolean;
    message:   string;
    data:      Datum[];
}

export interface Datum {
    username:    string;
    userImage:   string;
    postId:      number;
    cretedDate:  string;
    postTitel:   string;
    postContent: string;
    postImage:   string;
    comments:    Comment[];
    isLiked?: boolean;
    likeCount:number;
    commentCount:number;
}

export interface Comment {
    commentId:          number;
    commentContent:     string;
    commentCreatedDate: string;
    commentUserName:    string;
    commentUserImage:   string;
}
