// Generated by https://quicktype.io

export interface UserResponse {
    isSuccess: boolean;
    message:   string;
    data:      UserDetails[];
}

export interface UserDetails {
    image:                string;
    userType:             number;
    fullName:             string;
    confirmationCode:     number;
    savedPlants:          null;
    comments:             any[];
    likePosts:            null;
    id:                   string;
    userName:             string;
    normalizedUserName:   null;
    email:                string;
    normalizedEmail:      null;
    emailConfirmed:       boolean;
    passwordHash:         string;
    securityStamp:        string;
    concurrencyStamp:     string;
    phoneNumber:          string;
    phoneNumberConfirmed: boolean;
    twoFactorEnabled:     boolean;
    lockoutEnd:           null;
    lockoutEnabled:       boolean;
    accessFailedCount:    number;
}
