// Generated by https://quicktype.io

export interface CategoryResponse {
    isSuccess: boolean;
    message:   string;
    data:      CategoryDetails[];
}

export interface CategoryDetails {
    id:           number;
    categoryName: string;
    description:  string;
    image:        string;
}
