// Generated by https://quicktype.io

export interface GetAllPlantsResponse {
    isSuccess: boolean;
    message:   string;
    data:      PlantsDetails[];
}

export interface PlantsDetails {
    plantId:             number;
    plantName:           string;
    plantDescription:    string;
    plantSeason:         string;
    plantCareDetails:    string;
    plantMedicalBenefit: string;
    plantCategory:       string;
    plantImage:          string;
    isSaved?: boolean
}
