// Generated by https://quicktype.io

export interface AddPlantResponse{
    isSuccess: boolean,
    message:string,
    data: PlantDetails
}
export interface PlantDetails {
    id:             number;
    plantName:      string;
    description:    string;
    image:          string;
    careDetails:    string;
    season:         string;
    medicalBenefit: string;
    categoryId:     number;
    category:       null;
}
